version: "3.9"

services:
  backend:
    build: ./api
    container_name: insight-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./app
    container_name: insight-frontend
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://backend:8000
    depends_on:
      - backend
